fix: improve helm deploy logic (#46)
* fix: improve helm deploy logic
* ci: fix cleanup regardless if cancelled

---------

Co-authored-by: Glenn-Terjesen <Glenn-Terjesen@users.noreply.github.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,14 +28,58 @@ jobs:
       cancel-in-progress: true
     with:
       environment: dev
-      image: getting-started:test-helm-deploy.20240418-SHAd860147
+      image: getting-started:latest
       chart: fixture/helm/amazing-app
       release_name: amazing-app
       namespace: gha-ci
     secrets: inherit
+  test-deploy-gcp-with-rollback:
+    needs: [test-deploy-ok-gcp]
+    uses: ./.github/workflows/deploy.yml
+    concurrency:
+      group: ${{ github.head_ref }}-gcp
+      cancel-in-progress: true
+    with:
+      environment: dev
+      image: mybadimage:dummy
+      chart: fixture/helm/amazing-app
+      release_name: amazing-app
+      namespace: gha-ci
+      timeout_minutes: 6
+    secrets: inherit
+  verify-rollback-status:
+    if: success() || failure()
+    needs: [test-deploy-gcp-with-rollback]
+    runs-on: ubuntu-24.04
+    environment: dev
+    env:
+      HELM_DEPLOY_STATUS: ${{ needs.test-deploy-gcp-with-rollback.outputs.HELM_DEPLOY_STATUS }}
+    steps:
+      - run: |
+          if [ "${HELM_DEPLOY_STATUS}" != 2 ]; then
+            echo "Rollback failed"
+            exit 1
+          fi
+  test-deploy-gcp-no-image-update:
+    if: (success() || failure()) && needs.verify-rollback-status.result == 'success'
+    needs: [verify-rollback-status]
+    uses: ./.github/workflows/deploy.yml
+    concurrency:
+      group: ${{ github.head_ref }}-gcp
+      cancel-in-progress: true
+    with:
+      environment: dev
+      image: na
+      chart: fixture/helm/amazing-app
+      release_name: amazing-app
+      namespace: gha-ci
+      timeout_minutes: 6
+    secrets: inherit
 
   cleanup-deploy-gcp:
-    needs: [test-deploy-ok-gcp]
+    # run regardless of previous job status
+    if: always()
+    needs: [test-deploy-ok-gcp, test-deploy-gcp-no-image-update]
     runs-on: ubuntu-24.04
     environment: dev
     permissions:
@@ -76,6 +120,7 @@ jobs:
       namespace: ghaci
     secrets: inherit
   cleanup-deploy-azure:
+    if: always()
     needs: [test-deploy-ok-azure]
     runs-on: ubuntu-24.04
     environment: az-dev
@@ -109,19 +154,29 @@ jobs:
         run: |
           helm uninstall amazing-app -n ghaci
   update-lint-doc:
-    needs: [test-deploy-ok-azure, test-deploy-ok-gcp]
+    # run only if both test-deploy-ok-azure and test-deploy-gcp-no-image-update are successful, but ignore rollback failure
+    if: (success() || failure()) && needs.test-deploy-gcp-no-image-update.result == 'success' && needs.test-deploy-ok-azure.result == 'success'
+    needs:
+      [
+        cleanup-deploy-azure,
+        cleanup-deploy-gcp,
+        test-deploy-ok-azure,
+        test-deploy-gcp-no-image-update,
+      ]
     uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1
     with:
       workflow_file: .github/workflows/lint.yml
       readme_file: README-lint.md
   update-build-doc:
-    needs: [test-deploy-ok-azure, test-deploy-ok-gcp]
+    if: (success() || failure()) && needs.update-lint-doc.result == 'success'
+    needs: [update-lint-doc]
     uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1
     with:
       workflow_file: .github/workflows/deploy.yml
       readme_file: README-deploy.md
   update-unittest-doc:
-    needs: [test-deploy-ok-azure, test-deploy-ok-gcp]
+    if: (success() || failure()) && needs.update-build-doc.result == 'success'
+    needs: [update-build-doc]
     uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1
     with:
       workflow_file: .github/workflows/unittest.yml
diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,10 +1,11 @@
+---
 name: Entur/Helm/Deploy
 
 on:
   workflow_call:
     inputs:
       image:
-        description: "The image to deploy, on the form app:tag. Use `na` value to skip replacing the image version in the helm configuration."
+        description: "The image to deploy, on the form app:tag. Use `na` value to skip replacing the image version in the helm config."
         required: true
         type: string
       cloud_provider:
@@ -38,9 +39,13 @@ on:
         type: string
         description: "Do not use this input"
       timeout_minutes:
-        description: "Job timeout in minutes. Minimum is 3 minutes. Default is 15 minutes."
+        description: "Job timeout in minutes. Helm deploy timeout is half of this value to enable rollback. Default is 30 minutes."
         type: number
-        default: 15
+        default: 30
+    outputs:
+      HELM_DEPLOY_STATUS:
+        description: "Helm Deploy Status 0: Success, 1: Failed, 2: Rollback, 3: Rollback Failed"
+        value: ${{ jobs.helm-deploy.outputs.HELM_DEPLOY_STATUS }}
 jobs:
   helm-deploy:
     runs-on: ubuntu-24.04
@@ -71,6 +76,8 @@ jobs:
       AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
       AZURE_CLUSTER_NAME: ${{ vars.AZURE_CLUSTER_NAME  }}
       AZURE_CLUSTER_RESOURCE_GROUP: ${{ vars.AZURE_CLUSTER_RESOURCE_GROUP }}
+    outputs:
+      HELM_DEPLOY_STATUS: ${{ steps.helm-deploy.outputs.HELM_DEPLOY_STATUS }}
     steps:
       - id: verify-cloud-provider
         if: env.GHA_HELM_DEPLOY_CLOUD_PROVIDER != 'gcp' && env.GHA_HELM_DEPLOY_CLOUD_PROVIDER != 'az'
@@ -132,27 +139,60 @@ jobs:
           azure_cluster_resource_group: ${{ env.AZURE_CLUSTER_RESOURCE_GROUP }}
           azure_cluster_name: ${{ env.AZURE_CLUSTER_NAME }}
           azure_token: ${{ secrets.GITHUB_TOKEN }}
-      - id: deploy-given-tag
+      - id: helm-deploy
         name: Helm deploy ./${{ env.GHA_HELM_DEPLOY_CHART }}
         env:
           TIMEOUT: ${{ inputs.timeout_minutes }}
         shell: bash
         run: |
-          TIMEOUT=$((TIMEOUT-2))
+          TIMEOUT=$((TIMEOUT/2-2)) # Helm deploy timeout is half of the total job timeout minus two minutes for possible preparation time.
           helm dependency update ./${GHA_HELM_DEPLOY_CHART}
+          declare -a IMAGE_REPLACE_ARG
           if [ "${GHA_HELM_DEPLOY_IMAGE}" != "na" ]; then
-            helm upgrade ${GHA_HELM_DEPLOY_RELEASE_NAME} ./${GHA_HELM_DEPLOY_CHART}/ \
-              -f ${GHA_HELM_DEPLOY_CHART}/env/${GHA_HELM_DEPLOY_VALUES} \
-              --namespace ${GHA_HELM_DEPLOY_NAMESPACE} \
-              --set common.container.image=${GHA_HELM_DEPLOY_REGISTRY}/${GHA_HELM_DEPLOY_IMAGE} \
-              --install \
-              --timeout ${TIMEOUT}m0s \
-              --atomic
+            echo "Setting new image: ${GHA_HELM_DEPLOY_IMAGE}"
+            IMAGE_REPLACE_ARG+=("--set ")
+            IMAGE_REPLACE_ARG+=("common.container.image=\"${GHA_HELM_DEPLOY_REGISTRY}/${GHA_HELM_DEPLOY_IMAGE}\"")
+          fi
+          # Deploy the Helm chart
+          if helm upgrade "${GHA_HELM_DEPLOY_RELEASE_NAME}" "./${GHA_HELM_DEPLOY_CHART}" \
+            -f "${GHA_HELM_DEPLOY_CHART}/env/${GHA_HELM_DEPLOY_VALUES}" \
+            --namespace "${GHA_HELM_DEPLOY_NAMESPACE}" \
+            --install \
+            --wait \
+            --timeout "${TIMEOUT}m0s" \
+            --debug \
+            ${IMAGE_REPLACE_ARG[@]}
+          then
+            echo "#################################################################################################"
+            echo " Helm deployment successful."
+            echo "#################################################################################################"
+            echo "HELM_DEPLOY_STATUS=0" >> "$GITHUB_OUTPUT"
           else
-            helm upgrade ${GHA_HELM_DEPLOY_RELEASE_NAME} ./${GHA_HELM_DEPLOY_CHART}/ \
-              -f ${GHA_HELM_DEPLOY_CHART}/env/${GHA_HELM_DEPLOY_VALUES} \
-              --namespace ${GHA_HELM_DEPLOY_NAMESPACE} \
-              --install \
-              --timeout ${TIMEOUT}m0s \
-              --atomic
+            # check if we have previous Helm release
+            if helm list -n "${GHA_HELM_DEPLOY_NAMESPACE}" | grep -q "${GHA_HELM_DEPLOY_RELEASE_NAME}"
+            then
+              echo "#################################################################################################"
+              echo "Helm deployment failed. Rolling back to the previous version:"
+              echo "#################################################################################################"
+              if helm rollback "${GHA_HELM_DEPLOY_RELEASE_NAME}" --namespace "${GHA_HELM_DEPLOY_NAMESPACE}" --wait --timeout "${TIMEOUT}m0s" --debug
+              then
+                echo "#################################################################################################"
+                echo " Helm rollback completed... please investigate."
+                echo "#################################################################################################"
+                echo "HELM_DEPLOY_STATUS=2" >> "$GITHUB_OUTPUT"
+                exit 2
+              else
+                echo "#################################################################################################"
+                echo " Helm Rollback failed ... please investigate manually."
+                echo "#################################################################################################"
+                echo "HELM_DEPLOY_STATUS=3" >> "$GITHUB_OUTPUT"
+                exit 3
+              fi
+            else
+              echo "#################################################################################################"
+              echo "  Helm upgrade/install failed, but no previous Helm release found. Please investigate."
+              echo "#################################################################################################"
+              echo "HELM_DEPLOY_STATUS=1" >> "$GITHUB_OUTPUT"
+              exit 1
+            fi
           fi
