fix: injection fix, var fix

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -7,10 +7,14 @@ on:
         description: "The image to deploy, on the form app:tag. Use `na` value to skip replacing the image version in the helm configuration."
         required: true
         type: string
-      environment:
-        description: "The target environment"
-        required: true
+      cloud_provider:
+        description: "Which cloud service provider to use - Google Cloud: 'gcp' or Azure: 'az'"
         type: string
+        default: "gcp"
+      environment:
+        type: string
+        description: "GitHub environment to use Google Cloud: (dev, tst, prd) or Azure: (az-dev, az-test, az-prod)"
+        required: true
       chart:
         description: "The chart, defaults to `helm/$repository_name`"
         type: string
@@ -27,10 +31,6 @@ on:
         description: "The namespace to use, defaults to repository name"
         type: string
         default: "repo_name"
-      cloud_provider:
-        description: "Which repository to use. GCP/Azure"
-        type: string
-        default: "GCP"
       project_id:
         type: string
         description: "Do not use this input"
@@ -61,7 +61,24 @@ jobs:
       GHA_HELM_DEPLOY_NAMESPACE: ${{ inputs.namespace }}
       GHA_HELM_DEPLOY_ENV: ${{inputs.environment }}
       GHA_HELM_DEPLOY_REGISTRY: eu.gcr.io/entur-system-1287
+      GHA_HELM_DEPLOY_CLUSTER_NAME: ${{ inputs.cluster_name }}
+      # ignore "context access might be invalid" warning
+      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
+      GCP_SERVICE_ACCOUNT: ${{ vars.SERVICE_ACCOUNT }}
+      GCP_PROJECT_ID: ${{ inputs.project_id }}
+      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
+      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
+      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
+      AZURE_CLUSTER_NAME: ${{ vars.AZURE_CLUSTER_NAME  }}
+      AZURE_CLUSTER_RESOURCE_GROUP: ${{ vars.AZURE_CLUSTER_RESOURCE_GROUP }}
     steps:
+      - id: verify-cloud-provider
+        if: env.GHA_HELM_DEPLOY_CLOUD_PROVIDER != 'gcp' && env.GHA_HELM_DEPLOY_CLOUD_PROVIDER != 'az'
+        shell: bash
+        run: |
+          echo "Invalid cloud provider input: ${GHA_HELM_DEPLOY_CLOUD_PROVIDER}"
+          echo "Valid options are: 'gcp' or 'az'"
+          exit 1
       - id: set-release-name
         if: env.GHA_HELM_DEPLOY_RELEASE_NAME == 'repo_name'
         shell: bash
@@ -82,54 +99,70 @@ jobs:
         shell: bash
         run: |
           echo "GHA_HELM_DEPLOY_VALUES=values-kub-ent-${GHA_HELM_DEPLOY_ENV}.yaml" >> $GITHUB_ENV
-      - id: verify-cloud-provider
-        if: env.GHA_HELM_DEPLOY_CLOUD_PROVIDER != 'GCP' && env.GHA_HELM_DEPLOY_CLOUD_PROVIDER != 'Azure'
-        shell: bash
-        run: |
-          echo "cloud_provider can only be GCP or Azure"
-          exit 1
       - id: set-registry-azure
-        if: env.GHA_HELM_DEPLOY_CLOUD_PROVIDER == 'Azure'
+        if: env.GHA_HELM_DEPLOY_CLOUD_PROVIDER == 'az'
         shell: bash
         run: |
           echo "GHA_HELM_DEPLOY_REGISTRY=acrentur001.azurecr.io/entur" >> $GITHUB_ENV
+      - id: set-clustername-az
+        name: Set Cluster Name AKS
+        shell: bash
+        if: inputs.cloud_provider == 'az'
+        env:
+          GHA_HELM_DEPLOY_CLUSTER_NAME: ${{ env.GHA_HELM_DEPLOY_CLUSTER_NAME  }}
+        run: |
+          if [ -z "${GHA_HELM_DEPLOY_CLUSTER_NAME}" ]; then
+            echo "GitHub repository environment variable AZURE_CLUSTER_NAME is not set. Setup using tf-azure-apps. Exiting."
+            exit 1
+          fi
+          echo "GHA_HELM_DEPLOY_CLUSTER_NAME=${GHA_HELM_DEPLOY_CLUSTER_NAME}" >> $GITHUB_ENV
+      - id: set-clustername-gcp
+        name: Set Cluster Name GKE
+        shell: bash
+        if: inputs.cloud_provider == 'gcp'
+        env:
+          GHA_HELM_DEPLOY_CLUSTER_NAME: ${{ env.GHA_HELM_DEPLOY_CLUSTER_NAME  }}
+        run: |
+          if [ -z "${GHA_HELM_DEPLOY_CLUSTER_NAME}" ]; then
+            echo "GHA_HELM_DEPLOY_CLUSTER_NAME=kub-ent-${GHA_HELM_DEPLOY_ENVIRONMENT}-001" >> $GITHUB_ENV
+          else
+            echo "GHA_HELM_DEPLOY_CLUSTER_NAME=${GHA_HELM_DEPLOY_CLUSTER_NAME}" >> $GITHUB_ENV
+          fi
       - uses: actions/checkout@v4.1.6
       - id: install
         uses: azure/setup-helm@v4
-      - uses: entur/gha-meta/.github/actions/cloud-auth@v1.1.6
+      - uses: entur/gha-meta/.github/actions/cloud-auth@v1
         with:
           environment: ${{ env.GHA_HELM_DEPLOY_ENVIRONMENT }}
           cloud_provider: ${{ env.GHA_HELM_DEPLOY_CLOUD_PROVIDER }}
-          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
-          service_account: ${{ vars.SERVICE_ACCOUNT }}
-          azure_client_id: ${{ vars.AZURE_CLIENT_ID }}
-          azure_tenant_id: ${{ vars.AZURE_TENANT_ID }}
-          azure_subscription_id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
-      - uses: entur/gha-meta/.github/actions/k8s-auth@v1.1.6
+          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
+          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
+          azure_client_id: ${{ env.AZURE_CLIENT_ID }}
+          azure_tenant_id: ${{ env.AZURE_TENANT_ID }}
+          azure_subscription_id: ${{ env.AZURE_SUBSCRIPTION_ID }}
+      - uses: entur/gha-meta/.github/actions/k8s-auth@v1
         with:
           environment: ${{ env.GHA_HELM_DEPLOY_ENVIRONMENT }}
           cloud_provider: ${{ env.GHA_HELM_DEPLOY_CLOUD_PROVIDER }}
           project_id: ${{ inputs.project_id }}
-          cluster_name: ${{ inputs.cluster_name }}
-          azure_cluster_resource_group: ${{ vars.AZURE_CLUSTER_RESOURCE_GROUP }}
-          azure_cluster_name: ${{ vars.AZURE_CLUSTER_NAME }}
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+          cluster_name: ${{ env.GHA_HELM_DEPLOY_CLUSTER_NAME }}
+          azure_cluster_resource_group: ${{ env.AZURE_CLUSTER_RESOURCE_GROUP }}
       - id: deploy-given-tag
         name: Helm deploy ./${{ env.GHA_HELM_DEPLOY_CHART }}
         shell: bash
         run: |
-          helm dependency update ./${{ env.GHA_HELM_DEPLOY_CHART }}
-          if [ "${{ env.GHA_HELM_DEPLOY_IMAGE }}" != "na" ]; then
-            helm upgrade ${{ env.GHA_HELM_DEPLOY_RELEASE_NAME }} ./${{ env.GHA_HELM_DEPLOY_CHART }}/ \
-              -f ${{ env.GHA_HELM_DEPLOY_CHART }}/env/${{ env.GHA_HELM_DEPLOY_VALUES }} \
-              --namespace ${{ env.GHA_HELM_DEPLOY_NAMESPACE }} \
-              --set common.container.image=${{ env.GHA_HELM_DEPLOY_REGISTRY }}/${{ env.GHA_HELM_DEPLOY_IMAGE }} \
+          helm dependency update ./${GHA_HELM_DEPLOY_CHART}
+          if [ "${GHA_HELM_DEPLOY_IMAGE}" != "na" ]; then
+            helm upgrade ${GHA_HELM_DEPLOY_RELEASE_NAME} ./${GHA_HELM_DEPLOY_CHART}/ \
+              -f ${GHA_HELM_DEPLOY_CHART}/env/${GHA_HELM_DEPLOY_VALUES} \
+              --namespace ${GHA_HELM_DEPLOY_NAMESPACE} \
+              --set common.container.image=${GHA_HELM_DEPLOY_REGISTRY}/${GHA_HELM_DEPLOY_IMAGE} \
               --install \
               --atomic
           else
-            helm upgrade ${{ env.GHA_HELM_DEPLOY_RELEASE_NAME }} ./${{ env.GHA_HELM_DEPLOY_CHART }}/ \
-              -f ${{ env.GHA_HELM_DEPLOY_CHART }}/env/${{ env.GHA_HELM_DEPLOY_VALUES }} \
-              --namespace ${{ env.GHA_HELM_DEPLOY_NAMESPACE }} \
+            helm upgrade ${GHA_HELM_DEPLOY_RELEASE_NAME} ./${GHA_HELM_DEPLOY_CHART}/ \
+              -f ${GHA_HELM_DEPLOY_CHART}/env/${GHA_HELM_DEPLOY_VALUES} \
+              --namespace ${GHA_HELM_DEPLOY_NAMESPACE} \
               --install \
               --atomic
           fi
